apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: clean-arch-toten:local
          ports:
            - containerPort: 1337
          envFrom:
            - configMapRef:
                name: app-config
            #- secretRef:
                #name: app-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
